theme = "KoderCourse"
languageCode = "en-us"
baseurl = "https://Spawn.codes"
title = "Spawn.codes"
canonifyURLs = true

[params]
  name = "Spawn.codes"
  description = "Kurzy programovania pre deti."
  author = "Spawn.codes"
  authorEmail = "spawn.code@proton.me"
  authorImage = "/photo.png"
  autoDarkMode = false

  copyright = "Copyright Â© 2022 - Coder Â· All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Vitajte na Spawn.codes ğŸ‘‹"
  tagline = "Kurzy programovania"
  description = "StaÅˆ sa ~Code Wizard ğŸ§™â€â™‚ï¸~!"
  contact = "./prihlaska"

[[params.homepage.courses]]
  title = "ğŸ¥½ VirtuÃ¡lna Realita"
  color = "black"
  img = "https://raw.githubusercontent.com/googlecreativelab/webvr-musicalforest/master/static/img/aboutbg.gif"
  link = "/kurzy/vr"

[[params.homepage.courses]]
  title = "ğŸ“± MobilnÃ© AplikÃ¡cie"
  color = "black"
  img = "https://cdn.dribbble.com/users/462884/screenshots/2082445/tapandpay-gif.gif"
  link = "/kurzy/mobilne-aplikacie/"

[[params.homepage.courses]]
  title = "ğŸ¤– UmelÃ¡ Inteligencia"
  color = "black"
  img = "https://i.pinimg.com/originals/00/ad/14/00ad14740cc8f37d8c23eef53ef7681d.gif"
  link = "/kurzy/ml/"

[[params.homepage.courses]]
  title = "ğŸ Python"
  color = "white"
  img = "https://airnfts.s3.amazonaws.com/nft-images/20210525/Snake_game_1621964487458.gif"
  link = "/kurzy/python/"

[[params.homepage.courses]]
  title = "ğŸ® VÃ½voj Hier"
  color = "white"
  img = "https://i.pinimg.com/originals/bc/f9/7f/bcf97fc9066b06c6deb18dc6c155b155.gif"
  link = "/kurzy/vyvoj-hier/"

[params.homepage.resume]
  skills = ["ğŸ“… Å irokÃ¡ ponuka termÃ­nov", "ğŸ“˜ Å½iak dostane uÄebnicu", "ğŸ“œ CertifikÃ¡t o absolvovanÃ­", "ğŸ”° Online vyuÄovanie", "ğŸ¤ MalÃ© skupinky", "ğŸ‘©â€ğŸ« OchotnÃ­ lektori"]

[[params.homepage.resume.work]]
  name = "â“ Ako kurzy prebiehajÃº?"
  role = "ğŸ’¬ Å½iaci sa stretnÃº s lektorom na online hodine na vopred dohodnutej platforme (zvyÄajne Discord), kde sa potom spoloÄne uÄia podÄ¾a pripravenÃ½ch materiÃ¡lov."
  duration = ""

[[params.homepage.resume.work]]
  name = "â“ SÃº kurzy programovania nÃ¡roÄnÃ©?"
  role = "ğŸ’¬ VÅ¡etky kurzy sÃº robenÃ© tak, aby sa Å¾iak vedel chytiÅ¥ aj bez Å¾iadnych predoÅ¡lÃ½ch skÃºsenostÃ­ s programovanÃ­m. AvÅ¡ak ponÃºkame kurzy pre zaÄÃ­najÃºcich, ale aj skÃºsenejÅ¡Ã­ch programÃ¡torov. Pre zaÄiatoÄnÃ­kov preto odporÃºÄame kurzy ğŸ Python alebo ğŸ® VÃ½voj hier."
  duration = ""

[params.homepage.social]
  facebook = "https://www.facebook.com/profile.php?id=100085237996425"
  instagram = "https://www.instagram.com/spawn.codes/"
  discord = "https://discord.gg/nhUxuXjwvM"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
