theme = "KoderCourse"
languageCode = "en-us"
baseurl = "https://achatin.github.io/Koder"
title = "Koder"
canonifyURLs = true


[params]
  name = "Koder"
  description = "Kurzy programovania pre deti."
  author = "Koder"
  authorEmail = "koder@gmail.com"
  authorImage = "/photo.png"
  autoDarkMode = false

  copyright = "Copyright Â© 2022 - Coder Â· All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Vitajte na Koder.sk ğŸ‘‹"
  tagline = "Kurzy programovania"
  description = "PonÃºkame zaujÃ­mavÃ© kurzy programovania a informatiky pre deti a mladÃ½ch."
  contact = "./prihlaska"

[[params.homepage.courses]]
  title = "ğŸ¥½ VirtuÃ¡lna Realita"
  color = "black"
  img = "https://raw.githubusercontent.com/googlecreativelab/webvr-musicalforest/master/static/img/aboutbg.gif"
  link = "./kurzy/emoji-support"

[[params.homepage.courses]]
  title = "ğŸ“± MobilnÃ© AplikÃ¡cie"
  color = "black"
  img = "https://cdn.dribbble.com/users/462884/screenshots/2082445/tapandpay-gif.gif"
  link = "https://github.com/Achatin/Coding/tree/master/GO/Unfamiliar%20%5BBlocks%5D"

[[params.homepage.courses]]
  title = "ğŸ¤– Machine Learning"
  color = "black"
  img = "https://i.pinimg.com/originals/00/ad/14/00ad14740cc8f37d8c23eef53ef7681d.gif"
  link = "https://github.com/Achatin/Coding/tree/master/GO/Unfamiliar%20%5BBlocks%5D"

[[params.homepage.courses]]
  title = "ğŸ Python"
  color = "white"
  img = "https://airnfts.s3.amazonaws.com/nft-images/20210525/Snake_game_1621964487458.gif"
  link = "https://github.com/Achatin/Coding/tree/master/GO/Unfamiliar%20%5BBlocks%5D"

[[params.homepage.courses]]
  title = "ğŸ® VÃ½voj Hier"
  color = "white"
  img = "https://i.pinimg.com/originals/bc/f9/7f/bcf97fc9066b06c6deb18dc6c155b155.gif"
  link = "https://github.com/Achatin/Coding/tree/master/GO/Unfamiliar%20%5BBlocks%5D"

[params.homepage.resume]
  skills = ["ğŸ“… Å irokÃ¡ ponuka termÃ­nov", "ğŸ“˜ Å½iak dostane uÄebnicu", "ğŸ“œ CertifikÃ¡t o absolvovanÃ­", "ğŸ”° Online vyuÄovanie", "ğŸ¤ MalÃ© skupinky", "ğŸ‘©â€ğŸ« OchotnÃ­ lektori"]

[[params.homepage.resume.work]]
  name = "â“ Ako kurzy prebiehajÃº?"
  role = "ğŸ’¬ Å½iaci sa stretnÃº s lektorom na online hodine na vopred dohodnutej platforme (zvyÄajne Discord), kde sa potom spoloÄne uÄia podÄ¾a pripravenÃ½ch materiÃ¡lov."
  duration = ""

[[params.homepage.resume.work]]
  name = "â“ SÃº kurzy programovania nÃ¡roÄnÃ©?"
  role = "ğŸ’¬ VÅ¡etky kurzy sÃº robenÃ© tak, aby sa Å¾iak vedel chytiÅ¥ aj bez Å¾iadnych predoÅ¡lÃ½ch skÃºsenostÃ­ s programovanÃ­m. AvÅ¡ak ponÃºkame kurzy pre zaÄÃ­najÃºcich, ale aj skÃºsenejÅ¡Ã­ch programÃ¡torov. Pre zaÄiatoÄnÃ­kov preto odporÃºÄame kurzy ğŸ Python alebo ğŸ® VÃ½voj hier."
  duration = ""

[params.homepage.social]
  facebook = "https://facebook.com/"
  instagram = "https://twitter.com/"
  twitter = "https://instagram.com/"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
